config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :lists, only: [:show, :create, :index, :new] do
    resources :bookmarks, only: [:new, :create, :show]
  end
  resources :bookmarks, only: :destroy
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, presence: true, length: { minimum: 6 }
  validates_uniqueness_of :movie_id, :scope => [:movie_id, :list_id]
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, :overview, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    @bookmark = Bookmark.all
  end

  def show
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.save
    # No need for app/views/bookmarks/create.html.erb
    redirect_to bookmark_path(@bookmark)
  end

  def destroy
  end

  def new
    @bookmark = Bookmark.new(params[:id])
  end


  private

  def bookmark_params
    params.require(:bookmark).permit(:comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :destroy]
  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      render :new
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end


  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/destroy.html.erb
<h1>Bookmarks#destroy</h1>
<p>Find me in app/views/bookmarks/destroy.html.erb</p>

app/views/bookmarks/index.html.erb
<h1>Bookmarks#index</h1>
<p>Find me in app/views/bookmarks/index.html.erb</p>

app/views/bookmarks/new.html.erb
<h1>Bookmarks#new</h1>
<p>Find me in app/views/bookmarks/new.html.erb</p>
<%= simple_form_for @list.bookmark do |f| %>
      <%= f.input :title, required: false %>
      <%= f.input :overview %>
      <%= f.input :poster_url %>
      <%= f.input :rating %>
      <%= f.submit "Create a new bookmark" %>
    <% end %>

app/views/bookmarks/show.html.erb
<h1>Bookmarks#show</h1>
<p>Find me in app/views/bookmarks/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

<%= simple_form_for @list do |f| %>
  <%= f.input :name, required: true %>
<% end %>

app/views/lists/index.html.erb
<h1>Lists#index</h1>
<div class="container">
  <ul class="list-group">
  <% @lists.each do |list| %>
  <li class="list-group-item"> <%= link_to list.name, list_path(list) %></li>
  <% end %>
  <%= link_to "Create a list", new_list_path %>

  </ul>
</div>

app/views/lists/new.html.erb
<div class="container">
  <h1>Create a new list</h1>

  <%= simple_form_for @list do |f| %>
    <%= f.input :name, required: false %>
    <%= f.submit "create a list" %>
  <% end %>

</div>

app/views/lists/show.html.erb
<div class="container">
  <h1>Movies from list <%= @list.name %></h1>
    <div class="card" style="width: 18rem;">
      <% @list.bookmarks.each do |bookmark| %>
        <img src="<%= bookmark.movie.poster_url %>" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title"><%= bookmark.movie.title %></h5>
          <p class="card-text"><%= bookmark.movie.overview %></p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><%= bookmark.movie.rating %></li>
      <% end %>
        </ul>
      <div class="card-body">
        <a href="/lists/:list_id/bookmarks/new" class="card-link">create a bookmark</a>
        <a href="/bookmarks/:id" class="card-link">Delete</a>
      </div>
    <div class="action">
      <%# <%= link_to "Go Back", list_path %>
      <%# <%= link_to "Delete", %>
        <%# bookmark_path(@bookmark), %>
        <%# data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
    </div>
</div>